# 유니코드 및 기타 상수
F = "\x0c"
ESC = "\x1b\t"

CHAT_MESSAGE = ESC + "0005"
ENTRY_AND_EXIT_MESSAGE = ESC + "0004"
SUBSCRIBE_PERIOD_MESSAGE = ESC + "0127"
POONG_MESSAGE = ESC + "0018"
JOIN_THE_PAN_CLUB_MESSAGE = ESC + "0012"
